server:
  port: "53801"

# MySQL配置
mysql:
  host: "8.130.14.29"
  port: 33170
  username: "root"
  password: "zZ-szshyjbz16D"
  database: "easy_deploy"

# Redis配置
redis:
  host: "8.130.14.29"
  port: 36689
  password: "zZ-szshyjbz16D"  # 如果没有密码则留空
  db: 0

smtp:
  host: "smtp.qq.com"           # 发送邮件服务器
  user: "1293177585@qq.com"     # 自己的邮箱
  password: "wlkgcoyhwrfcffjj"  # 邮箱第三方客户端授权码
  from: "1293177585@qq.com"     # 发邮件人

websocket:
  port: 53801
  path: "/ws/docker"
  path_k8s: "/ws/k8s"
  read_buffer_size: 1024
  write_buffer_size: 1024